### ISSUE TITLE
Make this single-page

### ISSUE THREAD

**Issue by ankitr** [ProjectCopilot/projectcopilot.github.io#2]
It'd be neat to have a jQuery animation from "Learn more" to a information screen.

**Comment by ankitr** [comment]
I started doing this with two pages (as you can see in 7de3a8810ec8413aa960f172f7f9e22dc0e522d9), which was ok but not as cool. :-)

**Comment by ankitr** [comment]
I'm assigning this to @srustagi as a starter project so we can show investors substance on our pretty site.

**Comment by gmittal** [comment]
@srustagi, dang. A lot is riding on the quality of your work.

**Comment by ankitr** [comment]
@srustagi, if we don't raise any money it's your fault.

**Comment by gmittal** [comment]
Closed in #3
