### ISSUE TITLE
Retina favicon

### ISSUE THREAD

**Issue by ankitr** [ProjectCopilot/projectcopilot.github.io#22]
Our favicon looks blurry on Retina screens.
<img width="21" alt="screen shot 2016-10-23 at 2 46 26 pm" src="https://cloud.githubusercontent.com/assets/4143244/19629716/7a44c37c-992f-11e6-8d44-87490923f8ce.png">

**Comment by gmittal** [comment]
Are we keeping that as our final favicon?

**Comment by gmittal** [comment]
Giving this to @srustagi to fix.
