### ISSUE TITLE
Setup Donations

### ISSUE THREAD

**Issue by ankitr** [ProjectCopilot/projectcopilot.github.io#7]
Looks like PayPal and Stripe might both offer subsidized/free donations for nonprofits. I'll look into that and integrate it.

**Comment by gmittal** [comment]
Are we going with Stripe?

**Comment by gmittal** [comment]
We can also try [Square Cash](https://cash.me/).

**Comment by gmittal** [comment]
Status on this?

**Comment by ankitr** [comment]
We now have [this Square Cash address](cash.me/$cplt). I think a link on the site should be sufficient? I'm not sure if they expect/use more intensive integration.

**Comment by ankitr** [comment]
Closed with #21
